version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NOME=${DB_NOME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  db:
    image: mysql:8.4
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NOME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mysql_data:
